[meta]
name = "foo"
version = "13.3.7"
dependencies = []

[source]
download = [
	"https://anexcellenturl.com/anexcellentprogram.tar.gz",
]
local = [
	"patch1.patch",
	"patch2.patch",
]

sha256sums = [
	"fooooooooooooooooooooooooooooooooooooooooooooooooooo",
	"baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaar",
	"baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz",
]

[options]
strip = false
static = false 
parallel = true 

[[features]]
features = [
	["foo", "--enable-foo"],
	["bar", "--enable-bar"],
	["baz", "--enable-baz"],
]

[extra]
configure = [
	"--prefix=usr",
	"--exec-prefix=/usr",
]
prebuild = []
postbuild = []
