#!/bin/sh
curl -O http://www.connochaetos.org/oksh/oksh-0.5.0.tar.gz
bsdtar -xf oksh-0.5.0.tar.gz

cd oksh-0.5.0

./configure

make -j4

install -Dm755 ksh   ../TOTAR/bin/ksh
install -Dm755 ksh.1 ../TOTAR/usr/man/man1/ksh.1
