#!/bin/sh

# colorize
color() {
	color="$1"; shift
	text="$@"
	echo -n "[3${color}m${text}[00m"
}

lightcolor() {
	color="$1"; shift
	text="$@"
	echo -n "[9${color}m${text}[00m"
}

extract() {
	if [ -f "$1" ] ; then
		case "$1" in
			*.tar.bz2 | *.tbz2 | *.tar.gz | *.tgz | *.tar.xz | *.txz | *.zip | *.7z) bsdtar -xf "$1" ;;
			*.bz2) bunzip2 "$1" ;;
			*.gz) gunzip "$1" ;;
			*.rar) unrar x "$1" ;;
			*.tar) tar xvf "$1" ;;
			*.xz) xz -d "$1" ;;
			*.Z) uncompress "$1" ;;
			*) echo "Unable to extract $1." ;;
		esac
	else
		echo "Usage: extract $1"
	fi
}
